version: 2

build:
  image: latest
  apt_packages:
    - libproj-dev
    - proj-data
    - proj-bin
    - libgeos-dev

sphinx:
    configuration: docs/source/conf.py

python:
    version: 3.8
    install:
        - requirements: requirements.txt
        - method: pip
          path: .
