version: 2

build:
  image: latest

sphinx:
    configuration: docs/source/conf.py

python:
    version: 3.8
    install:
        - requirements: requirements.txt
        - method: pip
          path: .
